generatorName: perl
outputDir: samples/client/petstore/perl
inputSpec: modules/openapi-generator/src/test/resources/3_0/petstore-with-fake-endpoints-models-for-testing.yaml
additionalProperties:
  hideGenerationTimestamp: "true"
