generatorName: php-laravel
outputDir: bin/openapi3/../../samples/server/petstore/php-laravel
inputSpec: /Users/jim/projects/openapi-generator/bin/openapi3/../../modules/openapi-generator/src/test/resources/3_0/petstore.yaml
templateDir: bin/openapi3/../../modules/openapi-generator/src/main/resources/php-laravel
